state-of-the-art/BlendNet

BlendNet/Client.py
BlendNet/ManagerAgentWorker.py
BlendNet/ManagerTask.py
BlendNet/Workers.py
BlendNet/addon.py
BlendNet/providers/__init__.py
BlendNet/providers/gcp/__init__.py
BlendNet/script-render.py
__init__.py

Contains a number of commits with a small fixes

BN-1 A number of small fixes

---

BlendNet/AgentTask.py
BlendNet/ManagerTask.py

Now the tasks will be stopped by default until they are really finished

BN-2 Fixed issue with always completed tasks & naming conflict (#2)

---

BlendNet/AgentTask.py
BlendNet/ManagerTask.py

BN-8 Couple of fixes related to preview and merging (#8)

---

BlendNet/AgentTask.py
BlendNet/Client.py
BlendNet/FileCache.py
BlendNet/ManagerAgentWorker.py
BlendNet/ManagerTask.py
BlendNet/Server.py
BlendNet/TaskBase.py
BlendNet/TaskExecutorBase.py
BlendNet/addon.py
BlendNet/blend_file.py
BlendNet/providers/gcp/Instance.py
BlendNet/providers/gcp/__init__.py
__init__.py

fixes #8 
The change adds the task control interface "Actions" with stop/start/delete and info/messages/details buttons.
Also it fixes a number of different issues in the master branch - like errors in agents, proper handling of the agent task failure, disabling GCP terminate time wait since sometimes GCP kills the agent almost instantly and so on...
Also it updates the blender version on Manager/Agents to released 2.81.

Added minimal task control interface & fixed a number of issues (#1)

---

BlendNet/AgentTask.py
BlendNet/Client.py
BlendNet/Manager.py
BlendNet/ManagerAgentWorker.py
BlendNet/ManagerTask.py
BlendNet/TaskBase.py
BlendNet/TaskExecutorBase.py
BlendNet/blend_file.py
BlendNet/providers/gcp/__init__.py
BlendNet/script-render.py
__init__.py

* Fixed Agent bug with breaking stdout by threaded print
* Fixed Manager task issue with bad cleaning of failed Agent task
* Fixed remove from pending while stop of PENDING task
* Fixed fluid simulation getting cache issue
* Fixed missed blendnet_cache for last frame
* Fixed blender binary checksum & made it fatal
* Fixed issue with empty journal for manager and agent
* Fixed issue with UI - after rendering animation unable to render just one frame

BN-1 Added save and load tasks for the Manager and fixed a number of issues (#1)

---

BlendNet/Client.py
BlendNet/Manager.py
BlendNet/ManagerAgentWorker.py
BlendNet/Server.py
BlendNet/TaskBase.py
BlendNet/TaskExecutorBase.py
BlendNet/addon.py
BlendNet/script-render.py
__init__.py

* Agents termination when Manager is stopped
* Percentage of task complete in the tasks list
* Automatic downloading of the completed tasks results (without render preview)

BN-1 A number of important features

---

BlendNet/AgentTask.py
BlendNet/FileCache.py
BlendNet/ManagerAgentWorker.py
BlendNet/ManagerTask.py
BlendNet/TaskBase.py
BlendNet/TaskExecutorBase.py
BlendNet/Workers.py
__init__.py

* Added OOM kill catch and message provide to user (available in task info)
* Fixed issue with cancelling agent task during render scene preparation
* Fixed issue with not stopping agents if task was not actually started
* Added interface to determine Workers issues (upload/download...)
* Fixed samples acquired during task load
* Added check for task to verify files of the task

BN-2 Added ERROR task state to provide feedback to user (#2)

---

BlendNet/providers/gcp/__init__.py
__init__.py

Now the addon settings page will display the validation warnings about the GCP quotas according the current scene configuration (manager type, agent type and num of agents).
fixes #18

BN-18 Added information about invalid quota configs on addon settings page

---

BlendNet/blend_file.py

This realization can check the common cache files, but not all of them - because they are quite complicated. So all the additional caches will be just matched by glob and the frame number.
fixes: #21

BN-21 Added support for new mantaflow fluid simulator caches

---

BlendNet/addon.py
BlendNet/providers/__init__.py
__init__.py

Added a small button next to start/stop button of manager.
fixes: #26

BN-26 Added button to destroy the manager when it stopped

---

BlendNet/ManagerTask.py

Corrected the remaining time calculation algorithm. It's not supporting the changing of agents - but at least working without huge mistakes.
fixes: #34

BN-34 Fixed the incorrect calculation of remaining time

---

BlendNet/Client.py
BlendNet/addon.py
BlendNet/providers/__init__.py

It makes sure that the directory is existing before write file into.

BN-23 Fixed issue with downloading file to not existing directory

---

BlendNet/Manager.py
BlendNet/addon.py
BlendNet/providers/gcp/__init__.py
README.md
__init__.py

Now it's possible to select regular CPUs for agents and warnings when cheap VMs are not available.
fixes: #37

BN-37 Added automatic way to choose cheap VMs for agents

---

BlendNet/Client.py
BlendNet/addon.py
BlendNet/blend_file.py
BlendNet/providers/gcp/__init__.py

Now Windows support is completed and can pass the test-project rendering for 2.82 blender
fixes: #39

BN-39 Fixed a number of win issues (paths, ssl) and set lower default agent

---

BlendNet/Manager.py
BlendNet/ManagerAgentWorker.py
BlendNet/addon.py
BlendNet/providers/__init__.py
BlendNet/providers/aws/Agent.py
BlendNet/providers/aws/Instance.py
BlendNet/providers/aws/Manager.py
BlendNet/providers/aws/__init__.py
BlendNet/providers/gcp/__init__.py
BlendNet/script-render.py
README.md
__init__.py

The change adds pricing & spot instances - tested with test project and results are good.
fixes: #29

BN-29 First result of integrating the aws provider

---

BlendNet/Client.py
BlendNet/Manager.py
BlendNet/ManagerAgentWorker.py
BlendNet/ManagerClient.py
BlendNet/Server.py
BlendNet/addon.py
BlendNet/providers/aws/__init__.py
__init__.py
manager.py

BUGFIXES:
* Fixed issue with too long floats in price calc
* Fixed aws spot instance stopping in when there is no activity
fixes: #49

BN-49 Added listing logs for Manager and Agents right in the BlendNet UI interface

---

BlendNet/addon.py

BN-47 Improved the blender check available versions

---

BlendNet/Client.py
BlendNet/Manager.py
BlendNet/ManagerAgentWorker.py
BlendNet/ManagerClient.py
BlendNet/ManagerTask.py
BlendNet/Server.py
BlendNet/Workers.py
BlendNet/addon.py
BlendNet/providers/__init__.py
BlendNet/providers/aws/Processor.py
BlendNet/providers/aws/__init__.py
BlendNet/providers/gcp/Processor.py
BlendNet/providers/gcp/__init__.py
BlendNet/providers/local/Manager.py
BlendNet/providers/local/Processor.py
BlendNet/providers/local/__init__.py
README.md
__init__.py
agent.py
manager.py

Ok, the first version of Local provider - not perfect, but working)
fixes: #32

BN-32 First working version of the Local provider

---

BlendNet/Agent.py
BlendNet/Manager.py
BlendNet/ManagerAgentWorker.py
BlendNet/ManagerClient.py
BlendNet/addon.py
BlendNet/providers/InstanceProvider.py
BlendNet/providers/aws/Instance.py
BlendNet/providers/gcp/Instance.py
BlendNet/providers/gcp/__init__.py
BlendNet/providers/local/Manager.py
BlendNet/providers/local/Processor.py
BlendNet/providers/local/__init__.py
__init__.py
manager.py

* Added Agents status to the Addon UI
* That leaded to redesign the getResources on the Addon level - when the Manager becomes active Addon switching to it to scan the resources
fixes: #53

BN-53 Redesigned the Addon getresources system and added status of the Agents

---

BlendNet/addon.py

Found a bug in the filter change #42

BN-47 Fixed bug with not downloading the existing result

---

BlendNet/script-render.py
__init__.py

Still contain an issue with proper previewing the multilayer EXR (only the usual combined and depth here) - will check for a workaround, but basically that should be solved in blender itself.

BN-57 Fixed issue with producing the ml exr & previewing it in Addon UI

---

BlendNet/ManagerTask.py
BlendNet/addon.py
__init__.py

Now the info is displayed way better
related: #47

BN-47 Adjusted task info/details/messages to be displayed properly

---

.circleci/build.sh
.circleci/config.yml
.circleci/test_execute.sh
.circleci/test_prepare.sh
.circleci/test_run_service.sh
BlendNet/addon.py
BlendNet/blend_file.py
BlendNet/list_blender_versions.py
README.md

Basic build process for BlendNet
* Moved python logic to find the available blender versions to a separate module to use in CI
* Fixed issue with blend file validation
fixes: #68

BN-68 Added CircleCI configuration

---

BlendNet/FileCache.py
CHANGELOG.md
__init__.py

Prepared the release commit to move from dev version to v0.3
Also contains a couple of fixes for more stable rendering.
related: #47

Release v0.3

---

BlendNet/providers/aws/__init__.py
__init__.py

Prepared a quick fix for windows-based Addon blender
fixes: #75

BN-75 Fixed issue with AWS user-data file path on Windows

---

BlendNet/blend_file.py

Now it's checking the exception (ValueError produced by pathlib)

BN-77 Catching the not-relative dir during the project validation

---

BlendNet/addon.py
BlendNet/providers/aws/__init__.py

Also found a small bug with minimum on zero data
fixes: #81

BN-81 Fixed issue with show logs on windows

---

BlendNet/FileCache.py
manager.py

Some basic fixes to be able to start the manager and agent on Windows 10 x64
related: #84

BN-84 Basic windows fixes for Addon/Manager

---

BlendNet/Client.py
BlendNet/FileCache.py
BlendNet/ManagerTask.py
BlendNet/TaskExecutorBase.py
BlendNet/providers/local/Manager.py
BlendNet/script-compose.py
BlendNet/script-render.py
__init__.py

Together with #85 should make a good pair to fix: #84

BN-84 Fixes for file operations - windows is very picky here

---

BlendNet/addon.py
__init__.py

This was a huge one - wrong variable was used to download (always used the latest one to download).
Also fixed a couple of small UI issues
fixes: #96

BN-96 Fixed big issue with downloading the multiple tasks

---

BlendNet/addon.py
__init__.py

Slightly improved UI to clarify the Manager start/stop workflow.
fixes: #99

BN-99 Changed the UI to ensure the manager will be active before task run

---

.circleci/config.yml
.circleci/test_execute_addon.ps1
.circleci/test_prepare.ps1
.circleci/test_script_addon.py

BN-72 CircleCI of BlendNet for Windows platform

---

__init__.py

Just a simple checkbox to show/hide BlendNet UI in render panel
fixes: #103

BN-103 Added checkbox to show/hide the BlendNet render panel

---

.circleci/test_prepare.sh
BlendNet/Manager.py
BlendNet/Workers.py
BlendNet/__init__.py
BlendNet/addon.py
BlendNet/list_blender_versions.py
BlendNet/providers/__init__.py
BlendNet/providers/aws/__init__.py
BlendNet/providers/gcp/__init__.py
BlendNet/providers/local/__init__.py
__init__.py
agent.py
manager.py

* Moved Addon, Agent & Manager to the new choose model
* Now Addon will not show the BlendNet if the provider was not init properly, but will show just an error need to fix
* Improved getting the available Blender distributives with multi threaded workers
* Fixed non-critical issue with UI during Manager the startup listener
fixes: #86

BN-86 Moved from "autodetect provider" to "choose provider" model

---

.github/actions/blendnet-test-linux/action.yml
.github/actions/blendnet-test-linux/test_execute_addon.sh
.github/actions/blendnet-test-linux/test_execute_api.sh
.github/actions/blendnet-test-linux/test_prepare.sh
.github/actions/blendnet-test-linux/test_run_agent.sh
.github/actions/blendnet-test-linux/test_run_manager.sh
.github/actions/blendnet-test-linux/test_run_service.sh
.github/scripts/build.sh
.github/scripts/test_script_addon.py
.github/workflows/ci.yml
.github/workflows/nightly.yml

Rewritten the circleci logic to run on github
change for: #106

BN-106 Added github workflow realization

---

BlendNet/providers/aws/__init__.py
BlendNet/providers/gcp/__init__.py

Additional change to improve the GCP provider startup
fixes: #86

BN-86 Speed up the startup of GCP provider

---

.circleci/test_execute_addon.ps1
.circleci/test_execute_api.sh
.circleci/test_prepare.ps1
.circleci/test_prepare.sh
.circleci/test_run_service.sh
.circleci/test_script_addon.py
.github/actions/blendnet-test-linux/test_execute_api.sh
.github/actions/blendnet-test-linux/test_prepare.sh
.github/actions/blendnet-test-linux/test_run_service.sh
.github/scripts/test_script_addon.py
BlendNet/AgentTask.py
BlendNet/Client.py
BlendNet/Config.py
BlendNet/ManagerTask.py
BlendNet/Server.py
BlendNet/TaskBase.py
BlendNet/addon.py
BlendNet/blend_file.py
BlendNet/script-compose.py
BlendNet/script-render.py
BlendNet/utils.py
__init__.py

* Tested with modernized test-project
* BTW not pinging Manager if panel is disabled
TODO:
fixes: #102

BN-102 Migration to the advanced full paths schema

---

BlendNet/AgentTask.py
BlendNet/Client.py
BlendNet/ManagerTask.py
BlendNet/Server.py
BlendNet/list_blender_versions.py
BlendNet/providers/aws/__init__.py
__init__.py

* Each decode will try 2 times (utf8 & latin1)
* Improves logging capture of services on windows platform

BN-119 Decode & log fix for windows platform

---

BlendNet/TaskBase.py

Now it's fixed & working well)
fixes: #125

BN-125 Fixed issue with sys.executable - now it's working on 2.91.0

---

BlendNet/AgentTask.py
BlendNet/Client.py
BlendNet/ManagerTask.py
BlendNet/Server.py
BlendNet/list_blender_versions.py
BlendNet/providers/aws/__init__.py
BlendNet/providers/gcp/__init__.py
BlendNet/script-render.py

Now it should at least show the exception type if it was not catched properly...

BN-119 Added more unicode checks and better exception handling

---

.circleci/build.sh
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/scripts/build.sh
BlendNet/__init__.py
BlendNet/addon.py
BlendNet/providers/__init__.py
BlendNet/providers/aws/__init__.py
BlendNet/providers/gcp/__init__.py
BlendNet/providers/local/__init__.py
__init__.py
agent.py
manager.py

* Now it's possible to configure gcp/aws tool paths (gcloud/aws) from the Blender addon UI
* Small improvement to the CI build system and logging - added print version for Manager and Agent
fixes: #62

BN-62 Added provider settings to configure tool paths

---

BlendNet/Client.py

Added a missed url encode to the file upload client
fixes: #130

BN-130 Added urlencode to the file upload client

---

BlendNet/ManagerClient.py
BlendNet/SimpleREST.py

Fixed custom name for the agent as part of url
fixes: #132

BN-132 Fixed issue with agent name contains special chars

---

BlendNet/list_blender_versions.py

Small fix that should help with a manual error in the blender release process

BN-136 Prepared fix for blender release process inconsistency

---

BlendNet/providers/gcp/__init__.py

Simple change removed unnecessary Intel cpu select optimization in order to not cause issues on AMD and the other platforms.

BN-140 Removed gcp intel optimization due to issues on the other platforms

---

BlendNet/ManagerTask.py

Small fix imported from #30 due to v0.3 is affected too.
fixes: #148

BN-148 Fixed small error with subprocess import & increased timeout

---

.circleci/test_prepare.ps1
BlendNet/blend_file.py

This relatively simple change should add the support for external blend libraries linking.
fixes: #146

BN-146 Added simple support for the linked libraries and resources

---

BlendNet/providers/gcp/__init__.py

Fixed the credentials issue with the latest GCP gcloud SDK

BN-150 Updated to the changes in gcloud SDK 234.0.0

---

BlendNet/Server.py
BlendNet/addon.py
BlendNet/utils.py
__init__.py

Now the Addon also can capture it's logs and issues and show them just like Manager and Agents.

BN-152 Added a small button to show the addon log

---

BlendNet/providers/gcp/__init__.py

Found that GCP provider was broken due to the new updates in SDK.
fixes: #158

BN-156 Specified static discovery to False since not working by default

---

.circleci/test_execute_api.sh
.circleci/test_prepare.ps1
.github/actions/blendnet-test-linux/test_execute_addon.sh
.github/actions/blendnet-test-linux/test_execute_api.sh
BlendNet/AgentTask.py
BlendNet/script-render.py
__init__.py

BN-156 Blender v3 progressive by-default, so no need to use this option
